### PR TITLE
Add SNR parameter to background events

### PR DESCRIPTION
**Pull request by beasteers**
This change is [Reviewable](https://reviewable.io/reviews/justinsalamon/scaper/48)

### CODE REVIEW

**Comment by bensteers** [comment]
All of those commits except for the last should go away once you merge #40

**Comment by bensteers** [comment]
This is in reference to #47

**Comment by justinsalamon** [comment]
As noted on #47, SNR is relative so it doesn't make sense for a background track to have an SNR value. Super appreciate the contribution but perhaps best to first discuss in an issue, as I don't think I can merge this PR.

**Comment by justinsalamon** [comment]
Supporting this functionality, if we decide to, requires the solution to be carefully spec'd out prior to implementation. cf. discussion on #47.

Since this PR has diverged quite significantly from the master branch at this point (and since I think we should first converge on a design and only then implement it), I'm going to close this PR out.

Thanks again, hopefully we can get to this feature in the future!

**Pull request closed without merging**
